[pytest]
testpaths = tests
pythonpath = .
norecursedirs = agario .venv build
filterwarnings =
    ignore:.*Gym has been unmaintained.*:UserWarning
    ignore:.*ActorCriticPolicy which should be a MlpPolicy.*:UserWarning
    ignore:.*Not able to test alternative render modes.*:UserWarning

