blank_issues_enabled: false
contact_links:
  - name: Documentation Wiki
    url: https://github.com/Albin0903/build/tree/main/docs/wiki
    about: Consultez la documentation officielle du socle architectural avant d'ouvrir un ticket.

