// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"fr\" class=\"h-full bg-slate-50 text-slate-900\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/adapters/http/views/layout.templ`, Line: 9, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><!-- HTMX v2.0.10 --><script src=\"https://unpkg.com/htmx.org@2.0.10\" crossorigin=\"anonymous\"></script><!-- Tailwind CSS CDN for lightweight SSR pages --><script src=\"https://cdn.tailwindcss.com\"></script></head><body class=\"min-h-full flex flex-col font-sans antialiased selection:bg-blue-600 selection:text-white\"><!-- Barre supérieure produit --><header class=\"border-b border-slate-200/80 bg-white/90 backdrop-blur sticky top-0 z-40 shadow-xs\"><div class=\"max-w-6xl mx-auto px-4 sm:px-6 py-3.5 flex items-center justify-between\"><div class=\"flex items-center space-x-3\"><span class=\"inline-block w-2.5 h-2.5 rounded-full bg-blue-600 shadow-sm shadow-blue-500/30\"></span> <a href=\"/\" class=\"font-bold text-lg tracking-tight text-slate-900 hover:text-blue-600 transition-colors\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/adapters/http/views/layout.templ`, Line: 22, Col: 14}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</a></div><nav class=\"flex items-center space-x-4 text-sm font-medium\"><a href=\"/\" class=\"text-slate-600 hover:text-slate-900 transition-colors\">Accueil</a> <a href=\"/app/\" class=\"text-blue-600 hover:text-blue-700 transition-colors\">Console</a> <a href=\"/api/health\" target=\"_blank\" class=\"text-slate-400 hover:text-slate-600 font-mono text-xs\">Diagnostic</a></nav></div></header><!-- Scène principale : cible des swaps dynamiques HTMX --><main class=\"flex-1 max-w-6xl w-full mx-auto px-4 sm:px-6 py-8\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</main><!-- Pied de page produit discret (zéro jargon technique) --><footer class=\"border-t border-slate-200/80 bg-white/60 py-6 text-center text-xs text-slate-500\"><div class=\"max-w-6xl mx-auto px-4 sm:px-6 flex flex-col sm:flex-row items-center justify-between gap-2\"><p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/adapters/http/views/layout.templ`, Line: 43, Col: 15}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, " — Tous droits réservés.</p><p class=\"text-slate-400\">Interface Produit</p></div></footer><!-- Modales globales de l'application : situées HORS de <main> pour rester pérennes lors des swaps HTMX --><dialog id=\"rules-modal\" class=\"backdrop:bg-slate-900/40 backdrop:backdrop-blur-xs rounded-2xl border border-slate-200 bg-white text-slate-900 p-6 sm:p-8 max-w-lg w-full shadow-2xl shadow-slate-300/50 m-auto\"><div class=\"space-y-4\"><div class=\"flex items-center justify-between pb-3 border-b border-slate-100\"><h3 class=\"text-lg font-bold text-slate-900\">Règles & Fonctionnement</h3><button type=\"button\" onclick=\"document.getElementById('rules-modal').close()\" class=\"text-slate-400 hover:text-slate-700 text-lg font-bold px-2 py-0.5 rounded-lg hover:bg-slate-100 transition-colors\" aria-label=\"Fermer\">✕</button></div><div class=\"space-y-3 text-sm text-slate-600 leading-relaxed\"><p>Bienvenue dans votre application. Cet espace interactif permet d'accomplir vos activités dans un cadre structuré et accessible.</p><ul class=\"list-disc list-inside space-y-1.5 text-xs text-slate-500\"><li>Sélectionnez votre mode d'interaction dans l'en-tête produit.</li><li>Utilisez l'action primaire pour lancer ou valider une session.</li><li>Consultez l'indicateur d'état en temps réel pour suivre l'avancement.</li></ul></div><div class=\"pt-4 flex justify-end\"><button type=\"button\" onclick=\"document.getElementById('rules-modal').close()\" class=\"px-4 py-2 rounded-lg bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold shadow-sm transition-colors\">Compris</button></div></div></dialog><!-- Conteneur OOB (Out-Of-Band) pour modales dynamiques injectées par HTMX --><div id=\"modal-container\"></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
